Implement our own spell check action (#91)
Implement our own spell check action

diff --git a/.github/workflows/spellcheck.yml b/.github/workflows/spellcheck.yml
--- a/.github/workflows/spellcheck.yml
+++ b/.github/workflows/spellcheck.yml
@@ -11,5 +11,33 @@ jobs:
   spellchecking:
     runs-on: ubuntu-22.04
     steps:
-      - uses: actions/checkout@v3
-      - uses: streetsidesoftware/cspell-action@v2
+      - name: Checkout the code
+        uses: actions/checkout@v2
+        with:
+          # We need all history to list all changed files.
+          fetch-depth: 0
+      - name: Set up node
+        uses: actions/setup-node@v1
+        with:
+          node-version: "16"
+      - name: Install cspell
+        run: npm install --location=global cspell
+      - name: Run spell checking
+        run: |
+          # Add a problem matcher.
+          echo ::add-matcher::./.github/cspell_matcher.json
+          # Set internal field separator (filenames can have space in them).
+          IFS=$'\n'
+          # Find out which files were changed since master.
+          git diff --name-only origin/master..${{ github.event.after }} | { # Open sub-shell
+            # Spell check all files and remember if some failed.
+            EXIT_CODE=0
+            # Loop over the changed files.
+            while read CHANGED_FILE; do
+              # Run cspell on CHANGED_FILE, do not fail if the file is
+              # ignored or the spell-checking fails.
+              cspell --config ./cspell.json --no-must-find-files "$CHANGED_FILE" || EXIT_CODE=$?
+              echo $EXIT_CODE
+            done ;
+            exit $EXIT_CODE ; # Fail if some check failed.
+          } ;
