Do not stop after first failed file

diff --git a/.github/workflows/spellcheck.yml b/.github/workflows/spellcheck.yml
--- a/.github/workflows/spellcheck.yml
+++ b/.github/workflows/spellcheck.yml
@@ -23,6 +23,9 @@ jobs:
       - name: Install cspell
         run: npm install --location=global cspell
       - name: Run spell checking
+        id: run_spell_check
+        # Check all files and output all typos, failure is checked in the last step.
+        continue-on-error: true
         run: |
           # Add a problem matcher.
           echo ::add-matcher::./.github/cspell_matcher.json
@@ -34,3 +37,7 @@ jobs:
             # Run cspell on CHANGED_FILE, do not fail if the file is ignored.
             cspell --config ./cspell.json --no-must-find-files "$CHANGED_FILE"
           done
+      - name: Check for failures
+        # Fail the job if any of the spell checking failed.
+        if steps.run_spell_check.outcome != 'success'
+        run: exit 1
