Cleanup the bash

diff --git a/.github/workflows/spellcheck.yml b/.github/workflows/spellcheck.yml
--- a/.github/workflows/spellcheck.yml
+++ b/.github/workflows/spellcheck.yml
@@ -28,14 +28,16 @@ jobs:
           echo ::add-matcher::./.github/cspell_matcher.json
           # Set internal field separator (filenames can have space in them).
           IFS=$'\n'
-          # Spell check all files and remember if some failed.
-          EXIT_CODE=0
-          # Loop over all files changed since master.
-          { git diff --name-only origin/master..${{ github.event.after }} | { while read CHANGED_FILE; do
-            # Run cspell on CHANGED_FILE, do not fail if the file is ignored.
-            cspell --config ./cspell.json --no-must-find-files "$CHANGED_FILE" || EXIT_CODE=$?
-            echo $EXIT_CODE
-          done ; exit $EXIT_CODE ; } ; } ; EXIT_CODE=$?
-          # Debug exit code
-          echo $EXIT_CODE
-          exit $EXIT_CODE
+          # Find out which files were changed since master.
+          git diff --name-only origin/master..${{ github.event.after }} | { # Open sub-shell
+            # Spell check all files and remember if some failed.
+            EXIT_CODE=0
+            # Loop over the changed files.
+            while read CHANGED_FILE; do
+              # Run cspell on CHANGED_FILE, do not fail if the file is
+              # ignored or the spell-checking fails.
+              cspell --config ./cspell.json --no-must-find-files "$CHANGED_FILE" || EXIT_CODE=$?
+              echo $EXIT_CODE
+            done ;
+            exit $EXIT_CODE ; # Fail if some check failed
+          } ;
